### ISSUE TITLE
Internal server error

### ISSUE THREAD

**Issue by gedeon1989** [myflyingbox/woocommerce-plugin#8] opened 2017-06-29 13:06 UTC
Always showing internal server error in console when i try to create new shipment from woocommerce orders or trying to add new parcel. i test it in different themes and the same issue exist.
wp-admin/admin-ajax.php 500 (Internal Server Error)

**Comment by tbelliard** [comment] 2017-06-29 13:10
Do you have access to your server logs?
Internal server errors are general execution error. In this case this is probably related to some unanticipated set of conditions or an environment issue, but without the error log it will be quite difficult to debug.
Also if you provide more details about your setup (wordpress and woocommerce versions, to start with) this might help me reproduce the issue.

**Comment by gedeon1989** [comment] 2017-06-29 13:24
the logs i see are 
Invalid argument supplied for foreach() in my-flying-box/includes/meta-boxes/views/html-shipment-line.php on line 120, referer: http://my site/wp-admin/edit.php?post_type=shop_order

also Wprdpress version is 4.7.5 an woocommerce version 3.1.0

When i print $shopment I see that quote is empty so is empty $shipment->quote->offers also
[wc_order_id] => 751 [bulk_order_id] => [last_booking_error] => [quote] => [offer] => [collection_date] => [delivery_location_code] => [insured] =>

**Comment by gedeon1989** [comment] 2017-06-29 13:25
also Wprdpress version is 4.7.5 an woocommerce version 3.1.0

**Comment by gedeon1989** [comment] 2017-06-29 13:36
When i print $shopment I see that quote is empty so is empty $shipment->quote->offers also
  [wc_order_id] => 751 [bulk_order_id] => [last_booking_error] => [quote] => [offer] => [collection_date] => [delivery_location_code] => [insured] =>

**Comment by tbelliard** [comment] 2017-06-30 06:34
You seem to be on an edge case: if you don't even get a quote, there's an issue with the communication with our webservice. Even if you do not get offers (because the request route is not supported or you have specified dimensions exceeding our limits) you should still get a quote, and an empty array of offers.
Please ensure that you are using the correct credentials for the environment selected in the module settings. You must use the API credentials sent in your account confirmation email.
You can send us an email at tech@myflyingbox.com with your account ID or customer reference so we can go in more details and check our logs to see what's going on and guide you more precisely. I leave this ticket open for now because the module is definitely missing a clean error handling for this situation.

**Comment by gedeon1989** [comment] 2017-06-30 07:07
Is there something in Myflyingbox configuration that can cause this problem? Because I am connected to your server I think. In the menu Carrier services tab when i click Reload carriers from api I get all suggestions on my website if i have Wrong credentials I shouldn't connect to it Wright?

**Comment by tbelliard** [comment] 2017-06-30 07:11
Your analysis is correct, if you get results from the reload carriers button, then communication with the API probably works correctly. Can you send me your api login at tech@myflyingbox.com so I can check in our logs your request characteristics and try to reproduce the issue locally?

**Comment by gedeon1989** [comment] 2017-06-30 07:18
Ok I just send you my api login

**Comment by tbelliard** [comment] 2017-06-30 07:22
Thanks, received. From what I see in our logs, your quote requests do not contain postal code or city for the shipper. Please check that you fill in all default shipper information in the module configuration.
Let me know if this resolves the issue.

**Comment by gedeon1989** [comment] 2017-06-30 07:31
All the fields should be filed in Shipper information page to make api to work?

**Comment by tbelliard** [comment] 2017-06-30 07:34
At strict minimum City, postal code and country to get quotes (I think that's the cause of the error you got). Then to book a shipment: name, company name, street, phone and email are also mandatory, but these can be edited manually per shipment (it's just much easier to set them in the module config, as most of the time the pickup address will always be the same).

**Comment by gedeon1989** [comment] 2017-06-30 07:58
I fill all info and now i have this errors 
PHP Fatal error:  Call to a member function get_method_id() on null in wp-content/plugins/my-flying-box/includes/class-mfb-shipment.php on line 353
and the quote is empty again :(

**Comment by tbelliard** [comment] 2017-06-30 08:08
It seems you get all edge cases in one go :)
This error implies that the WC order on which you tried to initialize a shipment does not have any shipping method set... I did not think this was possible, but I managed to reproduce the error by simply removing the shipping line on an existing order.
I will correct the test to make sure that creating an MFB shipment works even when no shipping method is found at the order level.
Until then I'm afraid you will have to select a shipping method during the checkout process. If this is not possible in your use-case, please let me know and I will try to make the correction within the next couple of hours.

**Comment by gedeon1989** [comment] 2017-06-30 10:35
My case is that the customer shouldn't manage the shipping he will order and i will chose which shipping method to use from admin cp. is it possible or not?

**Comment by tbelliard** [comment] 2017-06-30 10:38
Yes it is, but I will need to correct this bug first. I'll try to do it shortly today. I will keep you updated when this is done.

**Comment by gedeon1989** [comment] 2017-06-30 10:41
ok thanks a lot

**Comment by tbelliard** [comment] 2017-06-30 19:01
I have published a new package, version 0.6. Please upgrade and test, your workflow should now be properly supported.
I'm closing the ticket now, but feel free to reopen if the issue is not solved for you, or open new tickets if you still encounter other problems with the module.

**Closed as completed by tbelliard** 2017-06-30 19:01 UTC
